### ISSUE TITLE
Allow the forking of many instances of a single container

### ISSUE THREAD

**Issue by earldouglas** [earldouglas/xsbt-web-plugin#191]
Inspired by http://stackoverflow.com/questions/26099002/how-to-launch-multiple-tomcat-instances-with-different-ports-per-spray-applicati

**Comment by Milyardo** [comment]
I think this task may be best achieved by implementing a configuration of sbt-revolver instead of reinventing managing multiple processes. Another option is the depend on sbt-core-next, which also contains many process management improvements like tasks to list processes that are currently in the background.

**Comment by earldouglas** [comment]
This is [now available](https://github.com/earldouglas/xsbt-web-plugin#running-multiple-containers) in version 3.0.0.

*build.sbt:*

```scala
containerScale := 5
```

Now, `<container>:start`, `<container>:quickstart`, and `<container>:debug` will fire up five instances of the container.
