### ISSUE TITLE
Deploy multiple WAR files into the same sbt

### ISSUE THREAD

**Issue by maugomez77** [earldouglas/xsbt-web-plugin#249]
I am a developer, I would like to be able to deploy on sbt in order to accelerate my development process multiple war files into the same tomcat instance if the port is not specified.

**Comment by earldouglas** [comment]
Can you elaborate on your configuration?  It sounds like you have a multi-module sbt project that includes multiple Web applications, and you want to build *.war* files for all of them, and deploy them to a single container via `tomcat:start`.  Is this correct?

Please pardon the late reply!

**Comment by maugomez77** [comment]
Yep that is correct

**Comment by maugomez77** [comment]
Yep I have different war file in a single project, so should be nice if there can be like a configuration to specify which projects are war file, and then in the root project just deploy those war files into a single tomcat instance, in order to have just one single instance to deploy and debugging.

**Comment by maugomez77** [comment]
Any news on this one?

**Comment by earldouglas** [comment]
There isn't a pretty way to do this.  I was thinking you could have one webapp project depend on the packaged artifact of another, and toss that into the arguments to jetty-runner, but sbt won't allow it, because one is a setting and the other is a task.

A workaround is to tell one of your webapps about all of the others, so that when you launch `jetty:start` on the one webapp, it also publishes the *.war* files of all the others.

Consider a project with two sub-modules: webapp1 and webapp2.  In *webapp2/build.sbt*, add the following:

```scala
containerArgs ++= Seq(
  "--path", "/webapp1",
  "/full/path/to/myproject/webapp1/target/scala-2.10/webapp1_2.10-0.1.0-SNAPSHOT.war",
  "--path", "/webapp2"
)
```

Now, launch webapp2 in sbt:

```
$ sbt
> project webapp1
> package
> project webapp2
> jetty:start
```

Now, webapp1 is available at *localhost:8080/webapp1*, and webapp2 is available at *localhost:8080/webapp2*.

This works, but it's ugly for several reasons:

1. It hijacks the `jetty:start` of one of the sub-modules, rather than defining a `jetty:start` for the top-level project
2. It requires you to manually package webapp1 so that webapp2 can find *webapp1.war*
3. It requires you to provide the full local path to *webapp1.war*

**Comment by earldouglas** [comment]
Oh, I see you're using Tomcat rather than Jetty.  Tomcat's runner also supports the `--path` argument, but I don't know if it supports multiple webapps like Jetty's runner does.  Let me know if you get it working.
