### ISSUE TITLE
How to remove module version from artifact name?

### ISSUE THREAD

**Issue by edmondo1984** [earldouglas/xsbt-web-plugin#316]
At the moment, I do not find an easy option to remove the version from artifactName. The problem with the current naming strategy is that every time you increase even a minor version, other services pointing at the webapp need to have their configuration updated.

Is there a way to package the app always with the same name?

**Comment by earldouglas** [comment]
> Is there a way to package the app always with the same name?

No; this packaging/release strategy is by design so that individual releases are always distinguishable, and is the convention across Scala and sbt libraries.

> every time you increase even a minor version, other services pointing at the webapp need to have their configuration updated

If you'd like to relax the strictness of version matching in your project configuration, you can use patterns from [Ivy's version matchers][1].

For example, to use the latest patch version under *2.1.x*:

```scala
addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "2.1.+")
```

Or to use the latest minor version under *2.x.y*:

```scala
addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "2.+")
```
[1]: http://ant.apache.org/ivy/history/latest-milestone/settings/version-matchers.html
