### ISSUE TITLE
container:start doesn't use unmanagedClasspath

### ISSUE THREAD

**Issue by mrArkwright** [earldouglas/xsbt-web-plugin#377]
I use `unmanagedClasspath` to add e.g. property files for local development setup to the classpath that shouldn't be included in the build or the repo. `container:quickstart` picks these up via `fullClasspath in Runtime`. Maybe it's a good idea to include `unmanagedClasspath in Runtime` in `container:start` for a more consistent behaviour between `start` and `quickstart`?

**Comment by earldouglas** [comment]
The goal for `start` is to behave similarly to a real deployment, which is why it goes to the trouble of preparing the webapp for packaging, including gathering all the classes and jar files.  Including non-deployment classpath resources seems like it would contradict this, so I don't know that we would want to do it.

The goal for `quickstart` is to start the container as quickly as possible for development purposes.

It makes sense that one might expect more consistent behavior between the two, but that hasn't been the goal.  Might it make sense to instead reduce `quickstart`'s classpath to more closely resemble that of `start`?

**Comment by mrArkwright** [comment]
Ah, I see the point in that.

What I'm trying to do is actually to resemble our deployment situation. Sensitive information that should not be part of the repository and that might differ from deployment to deployment is stored in property files in the resources directory. In production Jetty adds these to the classpath. Now I need a way to provide those files in development. Otherwise our application isn't able to boot. I thought `unmanagedClasspath` was the appropriate place for that, but I might be wrong and there might be a better way to do this.

**Comment by earldouglas** [comment]
That's an interesting use case, and sounds like a good approach.

Maybe the classpaths for both `start` and `quickstart` should be configurable by the user.  They could default to what they are today (or possibly exclude `unmanagedClasspath` from `quickstart` for consistency with `start`), and the user could add whatever they like via a new `containerClasspath += Seq(...)` setting.

What do you think?

**Comment by mrArkwright** [comment]
Sounds like a great solution!

**Comment by mrArkwright** [comment]
I would also argue that `quickstart` doesn't habe to exclude `unmanagedClasspath`. As you pointed out the goals for both commands are different so they are probably expected not to behave exactly the same way anyway.

**Comment by earldouglas** [comment]
Fixed by #907.  Will be included in version 5.0.0.
